### ISSUE TITLE
Currency with multiple symbols won't adjust cursor properly

### ISSUE THREAD

**Issue by LeoColman** [konstantin-lukas/intl-currency-input#1]
Hi!

I've noticed that using currencies that contain more than one symbol (such as BRL - R$) this component will not adjust the caret correctly.

Reproducing:

1. Open your codepen https://codepen.io/konstantin-lukas/pen/oNWzwOP
2. Add "currency: 'BRL'" to the options
3. Clear the text field
4. Start typing numbers

You'll see that the caret will be at this position:

![image](https://user-images.githubusercontent.com/1577251/128524743-4d56002c-4b6f-455d-bdf1-c68c133e2a81.png)

**Comment by konstantin-lukas** [comment]
***FIXED***
Thank you for reporting!

**Comment by LeoColman** [comment]
Thank you for this awesome lib!
Saved this backend dev a lot of time :D
