### ISSUE TITLE
Tab/ F5 not working when input is focused

### ISSUE THREAD

**Issue by jkatsiotis** [konstantin-lukas/intl-currency-input#3]
I think there needs to be a list of key chars that don't trigger the preventDefault function

**Comment by konstantin-lukas** [comment]
I'm pretty busy atm, though I think the idea is good. I actually thought about reworking the whole thing at some point cause the current code base is quite messy. In the meantime your are welcome to collab if you need that feature to be in the repo. I can update the npm package if necessary

**Comment by konstantin-lukas** [comment]
Version 2.0.0 fixes this by not using the preventDefault function at all anymore.
