### ISSUE TITLE
Option to always show the decimals

### ISSUE THREAD

**Issue by naq2** [konstantin-lukas/intl-currency-input#5]
Hi there,

An option to always shows a fixed number of decimals would be a nice plus whenever the time is right.

Thanks for the lib anyway.

Yours,

**Comment by konstantin-lukas** [comment]
Currently, the only features available are the ones visible in the documentation in the README file. A couple of months ago I wrote another formatting library called [moneydew ](https://github.com/konstantin-lukas/moneydew) which is going to be the basis for the planned rework of this library. It is also properly tested and doesn't rely on any WebAPI. It is however more like a formatting and money arithmetic library, so it doesn't automate the process of forcing a certain format on the input. Depending on your usecase you might however be able to use moneydew for your project. There's HTML documentation too and overall it's a much safer library to use.

**Comment by naq2** [comment]
Thx a lot.

**Comment by konstantin-lukas** [comment]
Check out version 2.0.0. There's a feature called "strict mode" which makes sure that there's always a fixed number of decimal places displayed. There's also a link to a CodePen in the README.md if you wanna try it first.
