### ISSUE TITLE
How to set defaultValue in 0.00?

### ISSUE THREAD

**Issue by curiosport** [konstantin-lukas/intl-currency-input#6]
I would like to have this text in the input by default:
**$0.00**

How do I do it? Currently I only get this:
**$0**

**Comment by konstantin-lukas** [comment]
Currently, the only features available are the ones visible in the documentation in the README file. A couple of months ago I wrote another formatting library called [moneydew ](https://github.com/konstantin-lukas/moneydew) which is going to be the basis for the planned rework of this library. It is also properly tested and doesn't rely on any WebAPI. It is however more like a formatting and money arithmetic library, so it doesn't automate the process of forcing a certain format on the input. Depending on your usecase you might however be able to use moneydew for your project. There's HTML documentation too and overall it's a much safer library to use.

When I rework this library your requested feature will however be available in this library too.

**Comment by konstantin-lukas** [comment]
I finished version 2.0.0. However, please have a look at the new documentation inside the docs folder before using. There have been some major changes to the interface.
